// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// MeGet implements GET /me operation.
//
// GET /me
func (UnimplementedHandler) MeGet(ctx context.Context) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context, req *User) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
